version: '3'

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    command:
      - --secure-file-priv=/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  ignite1:
    image: apacheignite/ignite:latest
    restart: unless-stopped

  ignite2:
    image: apacheignite/ignite:latest
    restart: unless-stopped

  webserver:
    image: zetman13/archi:task2
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      DB_PASSWORD: ${DB_PASSWORD}
      CACHE_SERVERS: "ignite1:10800,ignite2:10800"


