version: '3'

services:
  mysql:
    image: mysql:5.7.30
    restart: unless-stopped
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_LOGIN}
      MYSQL_PASSWORD: ${DB_PASSWORD}

  zookeeper:
    image: wurstmeister/zookeeper
    #container_name: zookeeper

  kafka:
    image: wurstmeister/kafka
    #container_name: kafka-node-1
    depends_on:
      - "zookeeper"
    #ports:
    #  - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      #KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  webserver:
    image: zetman13/archi:task4_webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - "mysql"
      - "kafka"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      QUEUE_HOST: ${QUEUE_HOST}
      QUEUE_TOPIC: ${QUEUE_TOPIC}
      QUEUE_GROUP_ID: ${QUEUE_GROUP_ID}

  worker:
    image: zetman13/archi:task4_worker
    restart: unless-stopped
    depends_on:
      - "mysql"
      - "kafka"
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_LOGIN: ${DB_LOGIN}
      QUEUE_HOST: ${QUEUE_HOST}
      QUEUE_TOPIC: ${QUEUE_TOPIC}
      QUEUE_GROUP_ID: ${QUEUE_GROUP_ID}
